assets: /home/mk/dev_ws/vla/pi0_TO_ws/src/openpi/third_party/libero/libero/libero/assets
bddl_files: /home/mk/dev_ws/vla/pi0_TO_ws/src/openpi/third_party/libero/libero/libero/bddl_files
benchmark_root: /home/mk/dev_ws/vla/pi0_TO_ws/src/openpi/third_party/libero/libero/libero
datasets: /home/mk/dev_ws/vla/pi0_TO_ws/src/openpi/third_party/libero/libero/libero/../datasets
init_states: /home/mk/dev_ws/vla/pi0_TO_ws/src/openpi/third_party/libero/libero/libero/init_files
